FROM python:3.13-slim

# Print Debian version during build
# RUN cat /etc/debian_version && \
#     cat /etc/os-release

WORKDIR /usr/src/app

ENV PYTHONPATH=/usr/src

# RUN rm -f /etc/apt/sources.list && \
#     echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ trixie main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
#     echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ trixie-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
#     echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security/ trixie-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list

# apt-get will try default mirrors first, then your custom mirror
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    ffmpeg \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt .

RUN pip install -i https://package-mirror.liara.ir/repository/pypi/simple -r requirements.txt

# Copy everything (not just ./app)
COPY ./app/ .

# Create __init__.py files to ensure proper Python package structure
# RUN find app -type d -exec touch {}/__init__.py \;