FROM python:3.13-slim

WORKDIR /usr/src/app

ENV PYTHONPATH=/usr/src

COPY ./requirements.txt .

RUN pip install -i https://pypi.devneeds.ir/simple/ -r requirements.txt

# Copy everything (not just ./app)
COPY ./app/ .

# Create __init__.py files to ensure proper Python package structure
# RUN find app -type d -exec touch {}/__init__.py \;