"""add_column_user_created_by_admin_id

Revision ID: 793815938b5c
Revises: 983dbdc4248a
Create Date: 2026-05-10 13:55:02.914888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793815938b5c'
down_revision: Union[str, Sequence[str], None] = '983dbdc4248a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_by_admin_id')
    # ### end Alembic commands ###
