"""change the pulic_id length to 8

Revision ID: adc0ad74192a
Revises: f7119e8b2616
Create Date: 2026-05-22 21:23:53.145883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc0ad74192a'
down_revision: Union[str, Sequence[str], None] = 'f7119e8b2616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'public_id',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_index(op.f('ix_videos_public_id'), table_name='videos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_public_id'), 'videos', ['public_id'], unique=True)
    op.alter_column('videos', 'public_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###
