"""remove_userrole_for_fix_a_bug

Revision ID: aea208a9a516
Revises: 7ced9dab186c
Create Date: 2026-05-10 12:21:06.954151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea208a9a516'
down_revision: Union[str, Sequence[str], None] = '7ced9dab186c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
