"""add column public id

Revision ID: f7119e8b2616
Revises: 2c0f45a2e185
Create Date: 2026-05-22 20:56:34.201869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7119e8b2616'
down_revision: Union[str, Sequence[str], None] = '2c0f45a2e185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'channels', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('videos', sa.Column('public_id', sa.String(length=11), nullable=False))
    op.create_index(op.f('ix_videos_public_id'), 'videos', ['public_id'], unique=True)
    op.create_foreign_key(None, 'videos', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'videos', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_public_id'), table_name='videos')
    op.drop_column('videos', 'public_id')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    # ### end Alembic commands ###
